class FoodItems {
  static const List<Map<String, dynamic>> foodItems = [
    {'name': "bread", 'title': "Bread", 'image': "bread.png", 'forDiabetes': false, 'forHeart': false, 'calories': 5000},
    {'name': "bun", 'title': "Bun", 'image': "bun.png", 'forDiabetes': false, 'forHeart': false, 'calories': 5000},
    {'name': "cup_cake", 'title': "Cup Cake", 'image': "cup_cake.png", 'forDiabetes': false, 'forHeart': false, 'calories': 5000},
    {'name': "cake", 'title': "Cake", 'image': "cake.png", 'forDiabetes': false, 'forHeart': false, 'calories': 5000},
    {'name': "short_eats", 'title': "Short Eats", 'image': "short_eats.jpg", 'forDiabetes': false, 'forHeart': false, 'calories': 5000},
    {'name': "banana", 'title': "Banana", 'image': "banana.png", 'forDiabetes': true, 'forHeart': true, 'calories': 5000},
    {'name': "avocado", 'title': "Avocado", 'image': "avacado.png", 'forDiabetes': true, 'forHeart': true, 'calories': 5000},
    {'name': "mango", 'title': "Mango", 'image': "mango.png", 'forDiabetes': true, 'forHeart': true, 'calories': 5000},
    {'name': "apple", 'title': "Apple", 'image': "apple.png", 'forDiabetes': true, 'forHeart': true, 'calories': 5000},
    {'name': "wood_apple", 'title': "Wood Apple", 'image': "wood_apple.jpg", 'forDiabetes': true, 'forHeart': true, 'calories': 5000},
    {'name': "watermelon", 'title': "Watermelon", 'image': "watermelon.png", 'forDiabetes': true, 'forHeart': true, 'calories': 5000},
    {'name': "lemon", 'title': "Lemon", 'image': "lemon.png", 'forDiabetes': true, 'forHeart': true, 'calories': 5000},
    {'name': "carrot", 'title': "Carrot", 'image': "carrot.png", 'forDiabetes': true, 'forHeart': true, 'calories': 5000},
    {'name': "pumpkin", 'title': "Pumpkin", 'image': "pumpkin.png", 'forDiabetes': true, 'forHeart': true, 'calories': 5000},
    {'name': "potato", 'title': "Potato", 'image': "potatoe.png", 'forDiabetes': true, 'forHeart': false, 'calories': 77},
    {'name': "tomato", 'title': "Tomato", 'image': "tomato.png", 'forDiabetes': true, 'forHeart': true, 'calories': 18},
    {'name': "onion", 'title': "Onion", 'image': "onion.png", 'forDiabetes': true, 'forHeart': true, 'calories': 40},
    {'name': "garlic", 'title': "Garlic", 'image': "garlic.png", 'forDiabetes': true, 'forHeart': true, 'calories': 149},
    {'name': "leeks", 'title': "Leeks", 'image': "leeks.png", 'forDiabetes': true, 'forHeart': true, 'calories': 61},
    {'name': "chili", 'title': "Chili", 'image': "chili.png", 'forDiabetes': true, 'forHeart': true, 'calories': 40},
    {'name': "meat", 'title': "Meat", 'image': "meat.png", 'forDiabetes': false, 'forHeart': false, 'calories': 250},
    {'name': "fish", 'title': "Fish", 'image': "fish.png", 'forDiabetes': true, 'forHeart': true, 'calories': 200},
    {'name': "egg", 'title': "Egg", 'image': "egg.png", 'forDiabetes': true, 'forHeart': true, 'calories': 78},
    {'name': "curry", 'title': "Curry", 'image': "curry.png", 'forDiabetes': false, 'forHeart': false, 'calories': 150},
    {'name': "mix_salad", 'title': "Mix Salad", 'salad.png': "salad.png", 'forDiabetes': true, 'forHeart': true, 'calories': 80},
    {'name': "sausages", 'title': "Sausages", 'image': "sausages.png", 'forDiabetes': false, 'forHeart': false, 'calories': 250},
    {'name': "banana_blossom", 'title': "Banana Blossom", 'image': "banana_blossom.png", 'forDiabetes': true, 'forHeart': true, 'calories': 100},
    {'name': "brinjal", 'title': "Brinjal", 'image': "brinjal.png", 'forDiabetes': true, 'forHeart': true, 'calories': 25},
    {'name': "papadum", 'title': "Papadum", 'image': "papadum.png", 'forDiabetes': true, 'forHeart': false, 'calories': 320},
    {'name': "kakiri", 'title': "Kakiri", 'image': "kakiri.jpg", 'forDiabetes': true, 'forHeart': true, 'calories': 33},
    {'name': "durian", 'title': "Durian", 'image': "URL", 'forDiabetes': false, 'forHeart': false, 'calories': 147},
    {'name': "donut", 'title': "Donut", 'image': "donut.png", 'forDiabetes': true, 'forHeart': false, 'calories': 250},
    {'name': "rice", 'title': "Rice", 'image': "rice.png", 'forDiabetes': true, 'forHeart': true, 'calories': 130},
    {'name': "cutlet", 'title': "Cutlet", 'image': "cutlet.png", 'forDiabetes': true, 'forHeart': false, 'calories': 300},
    {'name': "beans", 'title': "Beans", 'image': "URL", 'forDiabetes': true, 'forHeart': true, 'calories': 31},
    {'name': "bitter_gourd", 'title': "Bitter Gourd", 'image': "URL", 'forDiabetes': true, 'forHeart': true, 'calories': 17},
    {'name': "broccoli", 'title': "Broccoli", 'image': "URL", 'forDiabetes': true, 'forHeart': true, 'calories': 34},
    {'name': "sweet_potato", 'title': "Sweet Potato", 'image': "URL", 'forDiabetes': true, 'forHeart': true, 'calories': 90},
    {'name': "beetroot", 'title': "Beetroot", 'image': "URL", 'forDiabetes': true, 'forHeart': true, 'calories': 43},
    {'name': "okra", 'title': "Okra", 'image': "URL", 'forDiabetes': true, 'forHeart': true, 'calories': 33},
  ];
}